// <auto-generated>
/*
 * Ory Identities API
 *
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * Contact: office@ory.sh
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using LeanCode.Kratos.Client.Client;

namespace LeanCode.Kratos.Client.Model
{
    /// <summary>
    /// CredentialsCode represents a one time login/registration code
    /// </summary>
    public partial class KratosIdentityCredentialsCode
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KratosIdentityCredentialsCode" /> class.
        /// </summary>
        /// <param name="addressType">The type of the address for this code</param>
        /// <param name="usedAt">usedAt</param>
        [JsonConstructor]
        public KratosIdentityCredentialsCode(Option<string?> addressType = default, Option<DateTime?> usedAt = default)
        {
            AddressTypeOption = addressType;
            UsedAtOption = usedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AddressType
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressTypeOption { get; private set; }

        /// <summary>
        /// The type of the address for this code
        /// </summary>
        /// <value>The type of the address for this code</value>
        [JsonPropertyName("address_type")]
        public string? AddressType { get { return this.AddressTypeOption; } set { this.AddressTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of UsedAt
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UsedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsedAt
        /// </summary>
        [JsonPropertyName("used_at")]
        public DateTime? UsedAt { get { return this.UsedAtOption; } set { this.UsedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KratosIdentityCredentialsCode {\n");
            sb.Append("  AddressType: ").Append(AddressType).Append("\n");
            sb.Append("  UsedAt: ").Append(UsedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KratosIdentityCredentialsCode" />
    /// </summary>
    public class KratosIdentityCredentialsCodeJsonConverter : JsonConverter<KratosIdentityCredentialsCode>
    {
        /// <summary>
        /// The format to use to serialize UsedAt
        /// </summary>
        public static string UsedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="KratosIdentityCredentialsCode" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KratosIdentityCredentialsCode Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> addressType = default;
            Option<DateTime?> usedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address_type":
                            addressType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "used_at":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                usedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (addressType.IsSet && addressType.Value == null)
                throw new ArgumentNullException(nameof(addressType), "Property is not nullable for class KratosIdentityCredentialsCode.");

            return new KratosIdentityCredentialsCode(addressType, usedAt);
        }

        /// <summary>
        /// Serializes a <see cref="KratosIdentityCredentialsCode" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kratosIdentityCredentialsCode"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KratosIdentityCredentialsCode kratosIdentityCredentialsCode, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, kratosIdentityCredentialsCode, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KratosIdentityCredentialsCode" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="kratosIdentityCredentialsCode"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KratosIdentityCredentialsCode kratosIdentityCredentialsCode, JsonSerializerOptions jsonSerializerOptions)
        {
            if (kratosIdentityCredentialsCode.AddressTypeOption.IsSet && kratosIdentityCredentialsCode.AddressType == null)
                throw new ArgumentNullException(nameof(kratosIdentityCredentialsCode.AddressType), "Property is required for class KratosIdentityCredentialsCode.");

            if (kratosIdentityCredentialsCode.AddressTypeOption.IsSet)
                writer.WriteString("address_type", kratosIdentityCredentialsCode.AddressType);

            if (kratosIdentityCredentialsCode.UsedAtOption.IsSet)
                if (kratosIdentityCredentialsCode.UsedAtOption.Value != null)
                    writer.WriteString("used_at", kratosIdentityCredentialsCode.UsedAtOption.Value!.Value.ToString(UsedAtFormat));
                else
                    writer.WriteNull("used_at");
        }
    }
}
